2019-03-14 16:00:51,930 - IIot platform - ERROR - Object of type bytes is not JSON serializable
2019-03-14 17:08:57,859 - IIot platform - ERROR - 'ClientDevicesResponse' object has no attribute 'MessageToJson'
2019-03-14 17:09:50,072 - IIot platform - ERROR - 'ClientDevicesResponse' object has no attribute 'MessageToJson'
2019-03-15 10:31:54,390 - IIot platform - ERROR - Assignment not allowed to field "devicelist" in protocol message object.
2019-03-15 10:38:04,858 - IIot platform - ERROR - 'ClientDevicesResponse' object has no attribute 'add'
2019-03-15 16:28:46,575 - IIot platform - ERROR - 'DeviceDataRequest' object has no attribute 'getDevEuiList'
2019-03-15 17:09:31,816 - IIot platform - ERROR - get_bind() got an unexpected keyword argument 'list'
2019-03-15 17:10:25,999 - IIot platform - ERROR - get_bind() got an unexpected keyword argument 'list'
2019-03-15 17:11:58,627 - IIot platform - ERROR - get_bind() got an unexpected keyword argument 'list'
2019-03-15 17:12:19,320 - IIot platform - ERROR - get_bind() got an unexpected keyword argument 'list'
2019-03-15 17:12:30,236 - IIot platform - ERROR - get_bind() got an unexpected keyword argument 'lst'
2019-03-15 17:13:35,669 - IIot platform - ERROR - get_bind() got an unexpected keyword argument 'lst'
2019-03-15 17:16:13,471 - IIot platform - ERROR - get_bind() got an unexpected keyword argument 'lst'
2019-03-15 17:22:57,746 - IIot platform - ERROR - 'ResultProxy' object has no attribute 'fatchall'
2019-03-15 17:23:29,701 - IIot platform - ERROR - 'list' object has no attribute 'SerializeToString'
2019-03-18 11:30:40,129 - IIot platform - ERROR - get_bind() got an unexpected keyword argument 'lst'
2019-03-18 11:31:52,140 - IIot platform - ERROR - get_bind() got an unexpected keyword argument 'lst'
2019-03-18 14:34:33,175 - IIot platform - ERROR - getDeviceDataHistory() missing 2 required positional arguments: 'dev_lst' and 'ts'
2019-03-18 14:35:18,617 - IIot platform - ERROR - replace() argument 2 must be str, not google.protobuf.pyext._message.RepeatedScalarConta
2019-03-18 14:36:23,270 - IIot platform - ERROR - replace() argument 2 must be str, not Timestamp
2019-03-18 14:36:58,385 - IIot platform - ERROR - replace() argument 2 must be str, not int
2019-03-18 16:49:03,967 - IIot platform - ERROR - Assignment not allowed to field "ts" in protocol message object.
2019-03-18 16:50:47,132 - IIot platform - ERROR - datetime.datetime(2019, 3, 15, 10, 10, 39, 848637) has type datetime.datetime, but expected one of: int, long
2019-03-18 16:54:48,825 - IIot platform - ERROR - 1552633839.0 has type float, but expected one of: int, long
2019-03-18 16:55:09,848 - IIot platform - ERROR - Assignment not allowed to field "ts" in protocol message object.
2019-03-18 17:02:14,140 - IIot platform - ERROR - '26' has type str, but expected one of: int, long, float
2019-03-18 17:02:52,114 - IIot platform - ERROR - No positional arguments allowed
2019-03-18 17:17:47,737 - IIot platform - ERROR - 'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'append'
2019-03-20 10:38:13,411 - IIot platform - ERROR - 'EnumTypeWrapper' object has no attribute 'DEVICE_LIST_REQUEST'
2019-03-20 10:40:09,019 - IIot platform - ERROR - 'EnumTypeWrapper' object has no attribute 'DEVICE_LIST_REQUEST'
2019-03-20 10:52:01,963 - IIot platform - ERROR - 'EnumTypeWrapper' object has no attribute 'DEVICE_DATA_HISTORY_RESPONSE'
2019-04-12 17:51:09,245 - IIot platform - ERROR - invalid literal for int() with base 10: 'edb36d76-cd64-483c-a486-2306b47d6a74'
2019-04-12 17:56:42,402 - IIot platform - ERROR - invalid literal for int() with base 10: 'edb36d76-cd64-483c-a486-2306b47d6a74'
2019-04-12 17:58:04,705 - IIot platform - ERROR - invalid literal for int() with base 10: 'edb36d76-cd64-483c-a486-2306b47d6a74'
2019-04-12 17:58:42,826 - IIot platform - ERROR - invalid literal for int() with base 10: 'edb36d76-cd64-483c-a486-2306b47d6a74'
2019-04-12 18:05:57,836 - IIot platform - ERROR - 'edb36d76-cd64-483c-a486-2306b47d6a74' has type str, but expected one of: int, long
2019-04-12 18:06:29,215 - IIot platform - ERROR - 'edb36d76-cd64-483c-a486-2306b47d6a74' has type str, but expected one of: int, long
2019-04-12 18:08:39,607 - IIot platform - ERROR - 'edb36d76-cd64-483c-a486-2306b47d6a74' has type str, but expected one of: int, long
2019-04-12 18:09:13,706 - IIot platform - ERROR - 'edb36d76-cd64-483c-a486-2306b47d6a74' has type str, but expected one of: int, long
2019-04-15 10:35:06,043 - IIot platform - ERROR - profiles
2019-04-15 10:41:24,431 - IIot platform - ERROR - non-hexadecimal number found in fromhex() arg at position 8
2019-04-15 10:43:24,030 - IIot platform - ERROR - non-hexadecimal number found in fromhex() arg at position 8
2019-04-15 10:43:59,934 - IIot platform - ERROR - non-hexadecimal number found in fromhex() arg at position 8
2019-04-15 17:43:01,893 - IIot platform - ERROR - [Errno 2] No such file or directory: '/Users/kwak_yv/fullchain.pem'
2019-04-22 13:31:46,040 - IIot platform - ERROR - <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAUTHENTICATED
	details = "authentication failed: jwt parse error: signature is invalid"
	debug_error_string = "{"created":"@1555929106.040262000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"authentication failed: jwt parse error: signature is invalid","grpc_status":16}"
>
2019-04-22 13:32:51,662 - IIot platform - ERROR - <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAUTHENTICATED
	details = "authentication failed: jwt parse error: signature is invalid"
	debug_error_string = "{"created":"@1555929171.662318000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"authentication failed: jwt parse error: signature is invalid","grpc_status":16}"
>
2019-04-22 13:39:48,639 - IIot platform - ERROR - <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAUTHENTICATED
	details = "authentication failed: jwt parse error: signature is invalid"
	debug_error_string = "{"created":"@1555929588.639358000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"authentication failed: jwt parse error: signature is invalid","grpc_status":16}"
>
2019-04-22 13:54:17,687 - IIot platform - ERROR - <_Rendezvous of RPC that terminated with:
	status = StatusCode.ALREADY_EXISTS
	details = "object already exists"
	debug_error_string = "{"created":"@1555930457.687595000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"object already exists","grpc_status":6}"
>
2019-04-22 15:57:47,588 - IIot platform - ERROR - <_Rendezvous of RPC that terminated with:
	status = StatusCode.ALREADY_EXISTS
	details = "object already exists"
	debug_error_string = "{"created":"@1555937867.588092000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"object already exists","grpc_status":6}"
>
2019-04-22 18:34:53,726 - IIot platform - ERROR - type object 'Devicetype' has no attribute 'description'
2019-04-22 18:38:18,763 - IIot platform - ERROR - type object 'Devicetype' has no attribute 'description'
